Repository kiworkshop/snowball, pull requests merged in 2020-10, with the labels that each got.

#62 [#1] 유저 생성 기능 추가
  src/main/java/org/kiworkshop/snowball/user/controller/UserController.java
  src/main/java/org/kiworkshop/snowball/user/controller/dto/UserCreateRequestDto.java
  src/main/java/org/kiworkshop/snowball/user/controller/dto/UserCreateResponseDto.java
  src/main/java/org/kiworkshop/snowball/user/domain/User.java
  src/main/java/org/kiworkshop/snowball/user/repository/UserRepository.java
  src/main/java/org/kiworkshop/snowball/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/org/kiworkshop/snowball/user/controller/UserControllerTest.java
Labels: #백엔드, aggregate:회원

#65 [#1] 유저 조회 기능 추가
  .gitignore
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/org/kiworkshop/snowball/user/controller/UserController.java
  src/main/java/org/kiworkshop/snowball/user/controller/dto/UserLoginRequestDto.java
  src/main/java/org/kiworkshop/snowball/user/controller/dto/UserResponseDto.java
  src/main/java/org/kiworkshop/snowball/user/repository/UserRepository.java
  src/main/java/org/kiworkshop/snowball/user/service/UserModelMapper.java
  src/main/java/org/kiworkshop/snowball/user/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/static/docs/api-guide.html
  src/test/java/org/kiworkshop/snowball/ControllerTest.java
  src/test/java/org/kiworkshop/snowball/user/controller/UserControllerTest.java
  src/test/java/org/kiworkshop/snowball/util/ApiDocumentUtils.java
Labels: #백엔드, aggregate:회원

#79 [#2] 투자노트 CRUD 기능 구현
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/org/kiworkshop/snowball/SnowballApplication.java
  src/main/java/org/kiworkshop/snowball/common/advice/ControllerExceptionAdvice.java
  src/main/java/org/kiworkshop/snowball/common/config/JpaAuditingConfig.java
  src/main/java/org/kiworkshop/snowball/common/dto/ApiError.java
  src/main/java/org/kiworkshop/snowball/common/entity/BaseTimeEntity.java
  src/main/java/org/kiworkshop/snowball/common/exception/DomainServiceException.java
  src/main/java/org/kiworkshop/snowball/note/controller/NoteController.java
  src/main/java/org/kiworkshop/snowball/note/controller/dto/NoteAssembler.java
  src/main/java/org/kiworkshop/snowball/note/controller/dto/NoteCreateResponseDto.java
  src/main/java/org/kiworkshop/snowball/note/controller/dto/NotePageRequestDto.java
  src/main/java/org/kiworkshop/snowball/note/controller/dto/NoteRequestDto.java
  src/main/java/org/kiworkshop/snowball/note/controller/dto/NoteResponseDto.java
  src/main/java/org/kiworkshop/snowball/note/entity/Note.java
  src/main/java/org/kiworkshop/snowball/note/entity/NoteRepository.java
  src/main/java/org/kiworkshop/snowball/note/service/NoteService.java
  src/main/java/org/kiworkshop/snowball/user/controller/UserController.java
  src/main/java/org/kiworkshop/snowball/user/controller/dto/UserAssembler.java
  src/main/java/org/kiworkshop/snowball/user/controller/dto/UserCreateRequestDto.java
  src/main/java/org/kiworkshop/snowball/user/controller/dto/UserCreateResponseDto.java
  src/main/java/org/kiworkshop/snowball/user/entity/User.java
  src/main/java/org/kiworkshop/snowball/user/entity/UserRepository.java
  src/main/java/org/kiworkshop/snowball/user/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/static/docs/api-guide.html
  src/test/java/org/kiworkshop/snowball/ControllerTest.java
  src/test/java/org/kiworkshop/snowball/SnowballApplicationTests.java
  src/test/java/org/kiworkshop/snowball/common/advice/ControllerExceptionAdviceTest.java
  src/test/java/org/kiworkshop/snowball/note/controller/NoteControllerTest.java
  src/test/java/org/kiworkshop/snowball/note/controller/dto/NoteRequestDtoFixture.java
  src/test/java/org/kiworkshop/snowball/note/entity/NoteFixture.java
  src/test/java/org/kiworkshop/snowball/note/entity/NoteTest.java
  src/test/java/org/kiworkshop/snowball/note/entity/PageNoteFixture.java
  src/test/java/org/kiworkshop/snowball/note/service/NoteServiceTest.java
  src/test/java/org/kiworkshop/snowball/user/Entity/UserFixture.java
  src/test/java/org/kiworkshop/snowball/user/controller/UserControllerTest.java
  src/test/java/org/kiworkshop/snowball/user/controller/dto/UserCreateRequestDtoFixture.java
  src/test/java/org/kiworkshop/snowball/user/controller/dto/UserResponseDtoFixture.java
  src/test/java/org/kiworkshop/snowball/user/service/UserServiceTest.java
Labels: #백엔드, aggregate:투자노트

#80 [#38] 투자노트 작성 API 및 API 기초 구조 구축
  src/frontend/public/index.html
  src/frontend/src/App.tsx
  src/frontend/src/component/base/CreateNoteButton.tsx
  src/frontend/src/component/base/Nav.tsx
  src/frontend/src/component/note/CreateNoteBanner.tsx
  src/frontend/src/container/login/LoginContainer.tsx
  src/frontend/src/container/note/EditorContainer.tsx
  src/frontend/src/container/note/NoteListContainer.tsx
  src/frontend/src/lib/api/note.ts
  src/frontend/src/lib/api/user.ts
  src/frontend/src/lib/async.ts
  src/frontend/src/pages/CreateNote.tsx
  src/frontend/src/pages/Login.tsx
  src/frontend/src/pages/Main.tsx
  src/frontend/src/pages/Page404.tsx
  src/frontend/src/pages/index.tsx
  src/frontend/src/routes.ts
  src/frontend/src/static/images/snowman.svg
  src/frontend/src/type/note.d.ts
Labels: #프론트엔드, aggregate:투자노트

#85 [#75] [#76] 노트 수정 및 삭제
  src/frontend/.gitignore
  src/frontend/package.json
  src/frontend/public/index.html
  src/frontend/src/App.tsx
  src/frontend/src/component/base/Base.test.tsx
  src/frontend/src/component/base/Container.tsx
  src/frontend/src/component/base/CreateNoteButton.tsx
  src/frontend/src/component/base/Nav.tsx
  src/frontend/src/component/login/Login.test.tsx
  src/frontend/src/component/login/Login.tsx
  src/frontend/src/component/note/CreateNoteBanner.tsx
  src/frontend/src/component/note/Editor.tsx
  src/frontend/src/component/note/Note.test.tsx
  src/frontend/src/component/note/Note.tsx
  src/frontend/src/component/note/NoteList.tsx
  src/frontend/src/container/base/NavContainer.tsx
  src/frontend/src/container/login/LoginContainer.tsx
  src/frontend/src/container/note/CreateNoteBannerContainer.tsx
  src/frontend/src/container/note/EditorContainer.tsx
  src/frontend/src/container/note/NoteContainer.tsx
  src/frontend/src/container/note/NoteListContainer.tsx
  src/frontend/src/lib/api/note.ts
  src/frontend/src/lib/api/user.ts
  src/frontend/src/lib/async.ts
  src/frontend/src/pages/CreateNote.tsx
  src/frontend/src/pages/Login.tsx
  src/frontend/src/pages/Main.tsx
  src/frontend/src/pages/NoteDetail.tsx
  src/frontend/src/pages/Page404.tsx
  src/frontend/src/pages/UpdateNote.tsx
  src/frontend/src/pages/index.tsx
  src/frontend/src/routes.ts
  src/frontend/src/setupTests.ts
  src/frontend/src/static/dummyData.ts
  src/frontend/src/static/images/snowman.svg
  src/frontend/src/store/modules/user.ts
  src/frontend/src/type/note.d.ts
  src/frontend/src/type/user.d.ts
  src/frontend/yarn.lock
Labels: #프론트엔드, aggregate:투자노트
